// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models
{
    public partial class HrmEmployee
    {
        public decimal AutoId { get; set; }
        public string EmployeeId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public DateTime? DateOfBirth { get; set; }
        public string BloodGroupCode { get; set; }
        public string SexCode { get; set; }
        public string ReligionCode { get; set; }
        public string PresentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public string CompanyCode { get; set; }
        public string BranchCode { get; set; }
        public string DepartmentCode { get; set; }
        public string DesignationCode { get; set; }
        public string Luser { get; set; }
        public DateTime? Ldate { get; set; }
        public string Lip { get; set; }
        public string Lmac { get; set; }
        public DateTime? ModifyDate { get; set; }
        public string EmpPhoto { get; set; }
        public string FingerPrintId { get; set; }
        public string DigitalSignature { get; set; }
        public string NationalIdNo { get; set; }
        public string EmployeeStatus { get; set; }
        public string NationalityCode { get; set; }
    }
}