// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace GCTL.Data.Models
{
    public partial class ApplicationDbContext : DbContext
    {
        partial void OnModelCreatingPartial(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<HmsExpenseEntry>(entity =>
            {
                entity.Property(p => p.AutoId)
               .Metadata.SetAfterSaveBehavior(PropertySaveBehavior.Ignore);
            });
            modelBuilder.Entity<AccSubSubsidiaryLedger>(entity =>
            {
                entity.Property(p => p.AutoId)
               .Metadata.SetAfterSaveBehavior(PropertySaveBehavior.Ignore);
            });
            modelBuilder.Entity<AccSubsidiaryLedger>(entity =>
            {
                entity.Property(p => p.AutoId)
               .Metadata.SetAfterSaveBehavior(PropertySaveBehavior.Ignore);
            });
             modelBuilder.Entity<AccGeneralLedger>(entity =>
            {
                entity.Property(p => p.AutoId)
               .Metadata.SetAfterSaveBehavior(PropertySaveBehavior.Ignore);
            });
            modelBuilder.Entity<AccSubControlLedger>(entity =>
            {
                entity.Property(p => p.AutoId)
               .Metadata.SetAfterSaveBehavior(PropertySaveBehavior.Ignore);
            });
            modelBuilder.Entity<AccControlLedger>(entity =>
            {
                entity.Property(p => p.AutoId)
               .Metadata.SetAfterSaveBehavior(PropertySaveBehavior.Ignore);
            });

            modelBuilder.Entity<CoreBankAccountInformation>(entity =>
            {
                entity.Property(p => p.AutoId)
               .Metadata.SetAfterSaveBehavior(PropertySaveBehavior.Ignore);
            });
    
            modelBuilder.Entity<SalesDefBankBranchInfo>(entity =>
            {
                entity.Property(p => p.AutoId)
               .Metadata.SetAfterSaveBehavior(PropertySaveBehavior.Ignore);
            });

            modelBuilder.Entity<HrmDefDesignation>(entity =>
            {
                entity.Property(p => p.AutoId)
               .Metadata.SetAfterSaveBehavior(PropertySaveBehavior.Ignore);
            });
            modelBuilder.Entity<HrmDefDepartment>(entity =>
            {
                entity.Property(p => p.AutoId)
               .Metadata.SetAfterSaveBehavior(PropertySaveBehavior.Ignore);
            });
            modelBuilder.Entity<HrmDefReligion>(entity =>
            {
                entity.Property(p => p.AutoId)
               .Metadata.SetAfterSaveBehavior(PropertySaveBehavior.Ignore);
            });
            
            modelBuilder.Entity<HmsShift>(entity =>
            {
                entity.Property(p => p.AutoId)
               .Metadata.SetAfterSaveBehavior(PropertySaveBehavior.Ignore);
            });
            
            modelBuilder.Entity<SalesDefPaymentType>(entity =>
            {
                entity.Property(p => p.Tc)
               .Metadata.SetAfterSaveBehavior(PropertySaveBehavior.Ignore);
            });

            modelBuilder.Entity<RmgProdDefUnitType>(entity =>
            {
                entity.Property(p => p.Tc)
               .Metadata.SetAfterSaveBehavior(PropertySaveBehavior.Ignore);
            });

            modelBuilder.Entity<HrmEmployee>(entity =>
            {
                entity.Property(p => p.AutoId)
               .Metadata.SetAfterSaveBehavior(PropertySaveBehavior.Ignore);
            });

            modelBuilder.Entity<CoreUserInfo>(entity =>
            {
                // entity.Property(p => p.Id)
                //.Metadata.SetAfterSaveBehavior(PropertySaveBehavior.Ignore);
            });
        }
    }
}